### ISSUE TITLE
doAction with returns

### ISSUE THREAD

**Issue by MarcoBarlage** [MarcoDoemeland/5-in-a-row#3]
## Current behavior

Each bot is allowed to call the 'board.add_symbol' method to make the next move. But board doesn't check for multiple moves, which in turn enables cheating.

## Desired behavior

Players should make exactly 1 move!

## Proposal

Instead of 'doAction' having return type 'void', I would propose to return a positional type with only 1 position for the next move. The 'add_symbol' method should then be called and handled by the Game class

**Comment by JosephLemainque** [comment]
Sounds good!!
