### ISSUE TITLE
universal format for the board array seen by the players

### ISSUE THREAD

**Issue by MarcoBarlage** [MarcoDoemeland/5-in-a-row#4]
## Current behavior

Each round the player (whose turn it is) obtains the current status of the board represented by the char array, containing the symbols set so far.

## Downside of this approach

A priori the player only knows his symbol and not what the symbol of the opponent is respectively the default symbol for open boad tiles. One the one hand this is due to the fact, that only the players know their symbol (the board class doesn't seem to store the player symbols, don't it?) and on the other hand because the default symbol is stored as a private attribute within the board class.

## Proposal

Instead of passing an array with chars I would suggest passing a 'universal' version of it containing values of 1, 0 and -1, where 1 stands for the player whose turn it is and -1 for the its opponent. 0 represents empty board tiles.

## Argument for this universal representation

Using values 1,0 and -1 makes it independent of symbols used for the printing of the board. There is no necessity for passing the same format that will be printed later on. Therefore the player don't have to check for their symbol, the opponents symbol and the default symbol, making the program more universal in the sense that it is easier to understand and more robust.

**Comment by JosephLemainque** [comment]
Doing an array with 1's and -1's depending on which turn we are in seems even buggier to me. It would mean toggling each non-0 value each time, which is not performant. I understand your problematic, though. I solved it in my bot class using interpretation functions but I have no problem adapting the Board class to make it clearer and more robust.

**Alternative**
The Board class is given a symbol for each player (1 and 2) during construction. The array should contain the values 0 (no stone), 1 (stone from player 1) or 2 (stone from player 2). To make it even more robust, a enum class should be written to contain those 3 states. This way there is absolutely no ambiguity when extracting game data.
The PlayerBase should get an index during construction, telling whether it is player 1 or 2. Same, the valid variables should be defined in a enum class. Accessors should be written for the Game class to switch the value if necessary.
